# Generated by Django 4.2.16 on 2024-09-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_billablerate_timesheetfile_timesheetinvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_summary', models.JSONField()),
                ('project_total_costs', models.JSONField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.timesheetfile')),
            ],
        ),
    ]
