# Generated by Django 4.2.16 on 2024-09-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoicesummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetfile',
            name='is_fully_processed',
        ),
        migrations.AddField(
            model_name='timesheetfile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheetfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
